export { default as Cherry } from './Cherry'
export { default as Person } from './Person'
export { default as Remove } from './Remove'
export { default as CashierIcon } from './CashierIcon'
export { default as Settings } from './Settings'
