export { default as Cherry } from './Cherry'
export { default as Person } from './Person'
export { default as Remove } from './Remove'
export { default as CashierIcon } from './CashierIcon'
export { default as Settings } from './Settings'
export { default as Time } from './Time'
export { default as Dollar } from './Dollar'
export { default as Coins } from './Coins'
